#!/bin/bash
qemu-system-x86_64 \
	 \
	-m 10240 \
	-smp 4 \
	-drive file="images/fedora.qcow2",format=qcow2 \
	-cdrom "iso/Fedora-Everything-netinst-x86_64-41-1.4.iso" \
	-boot order=d \
	-net nic -net user \
	-display sdl
